// @ts-check
// `./.nuxt/eslint.config.mjs` is generated by the `@nuxt/eslint` module (see
// nuxt.config.ts) the first time you run `nuxt prepare` / `nuxt dev` /
// `nuxt build` — it already knows every auto-import Nuxt registers (ref,
// computed, useI18n, useHead, definePageMeta, component auto-imports, …) so
// none of that has to be hand-listed here as globals.
//
// NOTE on format: the house style this was modeled on names its config
// `.eslintrc.json` (the legacy ESLint format). ESLint 9 — already pinned in
// package.json, and required by @nuxt/eslint — defaults to flat config, and
// @nuxt/eslint's auto-import awareness (the whole reason no globals need
// hand-listing below) only works through this flat-config file. Rewriting
// this as a literal .eslintrc.json would mean dropping @nuxt/eslint and
// hand-listing every Nuxt/Vue auto-import as a global by hand — a real
// regression, not a formatting choice. Same rules, modern file.
import withNuxt from './.nuxt/eslint.config.mjs';
import localAttrOrder from './eslint-rules/attr-order.mjs';
import localCollapseEmpty from './eslint-rules/collapse-empty.mjs';

export default withNuxt(
  {
    plugins: {
      local: {
        rules: {
          'attr-order': localAttrOrder,
          'collapse-empty': localCollapseEmpty,
        },
      },
    },
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: 'module',
      globals: {
        // Standard ES2020+ global — declared explicitly since this project
        // doesn't otherwise pull in a Node/browser env preset that would
        // already include it.
        BigInt: 'readonly',
      },
    },
    rules: {
      // This codebase intentionally uses short, single-word component file
      // names (modal.vue, tag_list.vue) inside descriptively-named folders
      // rather than always-multi-word file names.
      'vue/multi-word-component-names': 'off',
      // Every prop, variable, and file in this codebase is snake_case by
      // deliberate house style (see use_locale_text, system_tile, etc.) —
      // vue/prop-name-casing's camelCase default would fight that everywhere
      // props are declared.
      'vue/prop-name-casing': 'off',
      // hero.title / cv_page.title and a few others deliberately render
      // translated `<em>`/`<br />` via v-html so emphasis can move per
      // locale (see the compilation.strictMessage note in nuxt.config.ts).
      'vue/no-v-html': 'off',
      '@typescript-eslint/no-explicit-any': 'warn',

      // --- house style below ---
      // Indent width/style, line endings, and charset are enforced via
      // .editorconfig instead of ESLint's core `indent` rule — that rule is
      // notoriously unreliable inside Vue SFC <script> blocks (a known
      // vue-eslint-parser pain point), so .editorconfig gets the same
      // outcome (every editor/IDE respects it) without the false positives.
      'linebreak-style': ['error', 'unix'],
      // Trailing whitespace/tabs at the end of a line are never
      // meaningful — applies file-wide, template markup included.
      'no-trailing-spaces': 'error',
      // No blank line(s) right before end-of-file — a file ends with
      // exactly one newline, not a trailing blank line.
      'no-multiple-empty-lines': ['error', { max: 1, maxEOF: 0 }],
      // Every if/else-if/else always gets braces, even for a single
      // statement, and the braced body always goes on its own line
      // (no `if (x) { doThing(); }` all on one line).
      curly: ['error', 'all'],
      'brace-style': ['error', '1tbs', { allowSingleLine: false }],
      quotes: ['error', 'single', { avoidEscape: true }],
      semi: ['error', 'always'],
      'no-var': 'error',
      'prefer-const': 'error',
      'prefer-arrow-callback': 'error',
      // console.error/warn/assert stay allowed (real diagnostics); console.log
      // does not — it's almost always debugging leftovers.
      'no-console': ['error', { allow: ['error', 'warn', 'assert'] }],
      '@typescript-eslint/no-unused-vars': ['error', {
        argsIgnorePattern: '^_',
        varsIgnorePattern: '^_',
      }],

      // --- Vue template attribute style ---
      // Elevated from @nuxt/eslint's default 'warn' to 'error' so these are
      // enforced, not just suggested.
      //
      // Attribute order: superseded by the custom local/attr-order rule
      // below, which sorts by exact attribute NAME per the house priority
      // list (class, id, name, v-if/else, is, title, ref, v-for, key,
      // type, href, to, target, src/alt, data-*, role/aria-*/tabindex,
      // value, v-text, v-html, placeholder, required, disabled,
      // width/height/controls, draggable/contenteditable/loading, style,
      // v-model, events last) — see eslint-rules/attr-order.mjs for the
      // full tier table and the few names it had to place by inference
      // (rel, the custom v-reveal directive, and custom component props
      // like :surface/:case_study/:doc, none of which are on that list).
      // vue/attributes-order can only sort by structural category (it
      // can't tell 'placeholder' from 'href'), so it's off to avoid the
      // two rules fighting over the same attributes.
      'vue/attributes-order': 'off',
      'local/attr-order': 'error',
      // Elements with fewer than 3 attributes and no inner content
      // collapse fully onto one line, closing tag included — see
      // eslint-rules/collapse-empty.mjs. vue/max-attributes-per-line
      // and vue/multiline-html-element-content-newline can only ever
      // split an over-long line, never merge one that's already
      // 'valid' under a looser cap, so this closes that gap.
      'local/collapse-empty': 'error',
      // Matches .editorconfig's 2-space indent, but for <template> markup
      // (the core `indent` rule only reaches <script>).
      // { alignAttributesVertically: false } so wrapped attributes get a
      // flat +2-space step from the tag's own indent, not vertically
      // aligned under the first attribute's column — that default ties
      // indent depth to how long the tag/component name happens to be
      // (e.g. 23 spaces for <CaseStudyCard ...>), which this house style
      // doesn't want.
      'vue/html-indent': ['error', 2, { alignAttributesVertically: false }],
      // Always v-on:click, never @click.
      'vue/v-on-style': ['error', 'longform'],
      // Always :class, never v-bind:class.
      'vue/v-bind-style': ['error', 'shorthand'],
      // Up to 2 attributes total stay on the tag's own line
      // (`<a class='x' href='y'>`); past that, the first attribute stays
      // beside the tag and every attribute after it gets its own line.
      'vue/max-attributes-per-line': ['error', {
        singleline: { max: 2 },
        multiline: { max: 1 },
      }],
      // The first attribute never drops to a new line under the tag name —
      // it stays beside it (`<a class='x'` not `<a\n  class='x'`) even once
      // later attributes wrap.
      'vue/first-attribute-linebreak': ['error', { multiline: 'beside', singleline: 'beside' }],
      // Empty *plain HTML* elements (<i></i>, <span></span>, ...) keep their
      // closing tag instead of self-closing — <i/> is only valid because
      // Vue's own template compiler reads it, not real HTML5, where a
      // trailing slash on a non-void element is meaningless. Void elements
      // (<img>, <input>, ...) and Vue components still self-close as usual.
      'vue/html-self-closing': ['error', {
        html: { normal: 'never', void: 'never', component: 'always' },
        svg: 'always',
        math: 'always',
      }],
      // An empty element (no text/children — v-text/v-html count as empty
      // here too, since they add no template child node) whose start tag
      // already wraps past 2 attributes gets its closing tag dropped to
      // its own line too, instead of gluing onto the last attribute's
      // line. { ignoreWhenEmpty: false } is what turns that on — the
      // rule's own default skips empty elements entirely. Left off for
      // <=2 attributes (those never reach 'multiline' in the first place,
      // so this rule doesn't apply to them at all).
      // { ignores: [] } clears the rule's default exemption for inline
      // elements (a/span/em/b/strong/...) — its own default skips those on
      // the theory that inline content should flow with surrounding text,
      // but in this codebase <a>/<span> are mostly structural wrappers
      // (card links, icon spans), not text runs, so they get the same
      // treatment as <p>/<div>: once the start tag wraps past 2
      // attributes, the content drops to its own line too.
      'vue/multiline-html-element-content-newline': ['error', { ignoreWhenEmpty: false, ignores: [] }],
      // No space before the closing '>' of a tag, but always a single
      // space before a self-closing '/>' (`<TagList :items="x" />`).
      'vue/html-closing-bracket-spacing': ['error', {
        startTag: 'never',
        endTag: 'never',
        selfClosingTag: 'always',
      }],
      // The closing bracket never drops to its own line, even once the
      // tag's attributes wrap — it always stays glued to the last
      // attribute (`... :aria-label="x">` not `...\n>`).
      'vue/html-closing-bracket-newline': ['error', { singleline: 'never', multiline: 'never' }],
      // Never more than one consecutive space, in attributes or
      // template expressions.
      'vue/no-multi-spaces': 'error',
    },
  },
  {
    ignores: ['scripts/**', 'public/**'],
  },
);
